Repository spinalcordtoolbox/spinalcordtoolbox, pull requests merged in 2018-02, with the labels that each got.

#1598 Add README.txt in deepseg_sc folder
  scripts/sct_download_data.py
Labels: installation

#1594 BUG: Fixed a small bug on None condition
  scripts/msct_image.py
Labels: bug, msct_image

#1601 Fix TensorFlow installation on Debian
  install/requirements/requirementsPip.txt
  install_sct
Labels: bug, installation

#1600 Adding minimal Dockerfile for SCT.
  contrib/docker/Dockerfile
  contrib/docker/README.md
Labels: enhancement, installation
