Repository spinalcordtoolbox/spinalcordtoolbox, pull requests merged in 2018-03, with the labels that each got.

#1637 Now possible to change data orientation on 4D data
  scripts/sct_image.py
Labels: enhancement, sct_image

#1638 Re-ordering of 4th dimension when apply transformation on 4D scans
  scripts/sct_apply_transfo.py
Labels: bug, sct_image

#1639 DOC: Moving contributing information to the repository.
  CONTRIBUTING.md
Labels: documentation, priority:LOW

#1629 Integration of SCT into fsleyes UI
  contrib/fsl_integration/README.md
  contrib/fsl_integration/sct_plugin.py
  documentation/imgs/logo_sct.png
Labels: feature

#1641 DOC: Adding sct_deepseg_gm citation to README.md
  README.md
Labels: documentation

#1646 [BUG] Fixing the TensorFlow installation for some old platforms.
  install/tf_distro_check.py
  install_sct
Labels: bug

#1648 Fslview no more called at the end of process if it it deprecated
  scripts/sct_utils.py
Labels: bug

#1657 Adding a port option for the qc server
  scripts/sct_qc.py
Labels: card:TO_REVIEW, enhancement

#1592 change raise style in msct_parser
  scripts/msct_parser.py
Labels: card:TO_REVIEW, enhancement, priority:MEDIUM
