Repository spinalcordtoolbox/spinalcordtoolbox, pull requests merged in 2019-12, with the labels that each got.

#2513 Spinal-level-based registration to the PAM50
  dev/spinal_level/create_PAM50_label_spinal_level.py
  scripts/sct_download_data.py
  scripts/sct_register_to_template.py
  scripts/sct_warp_template.py
  spinalcordtoolbox/metadata.py
  spinalcordtoolbox/vertebrae/core.py
  unit_testing/test_metadata.py
Labels: compatibility, sct_register_to_template

#2331 New method for detecting rotation in centermassrot
  scripts/msct_register.py
  scripts/sct_apply_transfo.py
  scripts/sct_register_multimodal.py
  scripts/sct_register_to_template.py
  spinalcordtoolbox/reports/qc.py
  spinalcordtoolbox/reports/slice.py
  testing/test_sct_register_multimodal.py
Labels: enhancement, sct_register_multimodal, sct_register_to_template

#2550 install/sct_changelog: Fixed bug when fetching previous release tag
  install/sct_changelog.py
Labels: installation

#2551 Added info for running SCT via Vbox
  README.md
Labels: documentation

#2558 Now using requirements-freeze.txt for installing stable releases
  install_sct
Labels: installation
