Repository spinalcordtoolbox/spinalcordtoolbox, pull requests merged in 2019-07, with the labels that each got.

#2315 Conversion from msct_parser to argparse
  scripts/sct_analyze_lesion.py
  scripts/sct_analyze_texture.py
  scripts/sct_apply_transfo.py
  scripts/sct_check_dependencies.py
  scripts/sct_compute_ernst_angle.py
  scripts/sct_compute_hausdorff_distance.py
  scripts/sct_compute_mscc.py
  scripts/sct_compute_mtr.py
  scripts/sct_compute_mtsat.py
  scripts/sct_compute_snr.py
  scripts/sct_concat_transfo.py
  scripts/sct_convert.py
  scripts/sct_create_mask.py
  scripts/sct_crop_image.py
  scripts/sct_label_vertebrae.py
  scripts/sct_register_multimodal.py
  scripts/sct_register_to_template.py
  scripts/sct_testing.py
  spinalcordtoolbox/utils.py
  testing/test_sct_analyze_lesion.py
  testing/test_sct_analyze_texture.py
  testing/test_sct_apply_transfo.py
  testing/test_sct_compute_ernst_angle.py
  testing/test_sct_compute_hausdorff_distance.py
  testing/test_sct_convert.py
  testing/test_sct_crop_image.py
  testing/test_sct_deepseg_gm.py
  testing/test_sct_deepseg_sc.py
  testing/test_sct_detect_pmj.py
  testing/test_sct_dice_coefficient.py
  testing/test_sct_dmri_separate_b0_and_dwi.py
  testing/test_sct_extract_metric.py
  testing/test_sct_get_centerline.py
  testing/test_sct_image.py
  testing/test_sct_propseg.py
  testing/test_sct_register_multimodal.py
  testing/test_sct_register_to_template.py
  testing/test_sct_resample.py
  unit_testing/test_transfo.py
Labels: msct_parser

#2299 Improve quality of straightening
  .gitignore
  scripts/sct_analyze_lesion.py
  scripts/sct_flatten_sagittal.py
  scripts/sct_get_centerline.py
  scripts/sct_label_utils.py
  scripts/sct_label_vertebrae.py
  scripts/sct_process_segmentation.py
  scripts/sct_register_to_template.py
  scripts/sct_straighten_spinalcord.py
  spinalcordtoolbox/centerline/core.py
  spinalcordtoolbox/centerline/curve_fitting.py
  spinalcordtoolbox/centerline/nurbs.py
  spinalcordtoolbox/deepseg_sc/core.py
  spinalcordtoolbox/process_seg.py
  spinalcordtoolbox/reports/assets/index.html
  spinalcordtoolbox/reports/qc.py
  spinalcordtoolbox/reports/slice.py
  spinalcordtoolbox/straightening.py
  unit_testing/create_test_data.py
  unit_testing/test_centerline.py
  unit_testing/test_process_seg.py
Labels: enhancement, sct_process_segmentation, sct_straighten_spinalcord

#2345 Remove not suported flag -k fromm install_sct
  install_sct
Labels: card:TO_REVIEW, fix:minor, priority:LOW

#2349 Refactor on install_sct
  .gitignore
  install_sct
Labels: card:TO_REVIEW, documentation, priority:LOW

#2350 Naming and conditionals refactor for /dev scripts
  dev/sct_average_multiecho.sh
  dev/sct_correct_header_mosaic.sh
Labels: card:TO_REVIEW, enhancement, priority:LOW

#2351 If statements refactor on git hooks
  dev/githook/install_pre_commit_hook.sh
  dev/githook/remove_pre_commit_hook.sh
Labels: card:TO_REVIEW, enhancement, priority:LOW

#2352 Refactor on batch_processing.sh
  batch_processing.sh
Labels: card:TO_REVIEW, enhancement, priority:LOW

#2355 Fix batch_processing, remove qc folder conditional failing
  batch_processing.sh
Labels: fix:minor, priority:HIGH

#2353 Refactor install_sct
  .gitignore
  install_sct
Labels: card:TO_REVIEW, enhancement, fix:minor, installation

#2360 Remove MPI functionality
  hpc/README.md
  hpc/cedar_template.sh
  hpc/gcp_template.sh
  hpc/guillimin_template.sh
  hpc/mammouth_template.sh
  hpc/pbs_template.sh
  hpc/slurm_template.sh
  install_sct
Labels: card:DO_NOT_MERGE!!!, card:TO_REVIEW, enhancement, priority:LOW

#2361 Add argparse module on shell scripts
  install_sct
  scripts/argparse.bash
Labels: enhancement, installation, priority:LOW

#2363 Make test_deepseg_lesion.py::test_intensity_normalization stable
  README.md
  unit_testing/test_deepseg_lesion.py
Labels: card:TO_REVIEW, sct_deepseg_lesion, testing

#2337 Continuation conversion from msct_parser to argparse
  scripts/sct_analyze_lesion.py
  scripts/sct_analyze_texture.py
  scripts/sct_apply_transfo.py
  scripts/sct_check_dependencies.py
  scripts/sct_compute_ernst_angle.py
  scripts/sct_compute_hausdorff_distance.py
  scripts/sct_compute_mscc.py
  scripts/sct_compute_mtr.py
  scripts/sct_compute_mtsat.py
  scripts/sct_compute_snr.py
  scripts/sct_concat_transfo.py
  scripts/sct_convert.py
  scripts/sct_create_mask.py
  scripts/sct_crop_image.py
  scripts/sct_deepseg_gm.py
  scripts/sct_deepseg_lesion.py
  scripts/sct_deepseg_sc.py
  scripts/sct_denoising_onlm.py
  scripts/sct_detect_pmj.py
  scripts/sct_dice_coefficient.py
  scripts/sct_dmri_compute_bvalue.py
  scripts/sct_dmri_compute_dti.py
  scripts/sct_dmri_concat_bvals.py
  scripts/sct_dmri_concat_bvecs.py
  scripts/sct_register_multimodal.py
  scripts/sct_register_to_template.py
  spinalcordtoolbox/deepseg_lesion/core.py
  spinalcordtoolbox/utils.py
  testing/test_sct_concat_transfo.py
  testing/test_sct_deepseg_gm.py
  testing/test_sct_dmri_concat_bvals.py
  testing/test_sct_dmri_concat_bvecs.py
Labels: card:DO_NOT_MERGE!!!, enhancement, msct_parser

#2365 Remove unused requirement files
  install/requirements/requirementsConda.txt
  install/requirements/requirementsMPI.txt
Labels: card:TO_REVIEW, priority:LOW

#2366 Support zsh configuration.
  install_sct
Labels: installation, priority:MEDIUM

#2370 batch_processing.sh: QC report is now generated locally
  batch_processing.sh
Labels: enhancement

#2374 Fixed creation of output folder and introduced new argparse class
  scripts/sct_analyze_lesion.py
  scripts/sct_analyze_texture.py
  scripts/sct_deepseg_lesion.py
  scripts/sct_deepseg_sc.py
  scripts/sct_detect_pmj.py
  spinalcordtoolbox/utils.py
Labels: enhancement
