Repository spinalcordtoolbox/spinalcordtoolbox, pull requests merged in 2025-02, with the labels that each got.

#4788 Pin `torch` to `<2.3` to keep versions in sync with Intel Mac platforms
  requirements.txt
Labels: installation

#4784 Allow ANTs binaries to access `msvc-runtime` DLLs to avoid DLL not found errors
  spinalcordtoolbox/utils/sys.py
Labels: installation

#4783 Replace monai-based contrast agnostic model to nnunet-based r20250204 release
  spinalcordtoolbox/deepseg/models.py
  spinalcordtoolbox/scripts/sct_deepseg.py
  testing/cli/test_sct_deepseg.py
Labels: sct_deepseg

#4796 Update `courses.rst` with SCT Course 2024 links
  documentation/source/user_section/courses.rst
Labels: documentation

#4802 Update `courses.rst`
  documentation/source/user_section/courses.rst
Labels: documentation

#4793 Upgrade Ubuntu 20.04 -> 22.04/24.04 in test suite
  .github/workflows/create-release.yml
  .github/workflows/release-body.md
  .github/workflows/test-batch-processing.yml
  .github/workflows/tests.yml
  documentation/source/user_section/installation/windows.rst
Labels: CI

#4780 Port "past release" fixes to the tags themselves, and remove them from the GHA workflow
  .github/workflows/test-past-releases.yml
Labels: installation
